# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nD6bx8IImSUfD6h8dCz3EGsfn0g_n1M3
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(
    page_title="CDS Flow Shop Scheduler",
    page_icon="🏭",
    layout="wide"
)

# ==================================================
# FUNGSI JOHNSON RULE
# ==================================================
def johnson_rule(df):

    jobs_front = []
    jobs_back = []

    temp = df.copy()

    while len(temp) > 0:

        min_a = temp["A"].min()
        min_b = temp["B"].min()

        if min_a <= min_b:
            idx = temp["A"].idxmin()
            jobs_front.append(temp.loc[idx, "Job"])
        else:
            idx = temp["B"].idxmin()
            jobs_back.insert(0, temp.loc[idx, "Job"])

        temp = temp.drop(idx)

    return jobs_front + jobs_back


# ==================================================
# COMPLETION MATRIX & MAKESPAN
# ==================================================
def calculate_completion(sequence, proc):

    jobs = len(sequence)
    machines = len(proc.columns)

    completion = pd.DataFrame(
        0,
        index=sequence,
        columns=proc.columns
    )

    for i, job in enumerate(sequence):

        for j, machine in enumerate(proc.columns):

            pt = proc.loc[job, machine]

            if i == 0 and j == 0:
                completion.loc[job, machine] = pt

            elif i == 0:
                completion.loc[job, machine] = (
                    completion.iloc[i, j-1] + pt
                )

            elif j == 0:
                completion.loc[job, machine] = (
                    completion.iloc[i-1, j] + pt
                )

            else:
                completion.loc[job, machine] = (
                    max(
                        completion.iloc[i-1, j],
                        completion.iloc[i, j-1]
                    ) + pt
                )

    makespan = completion.iloc[-1, -1]

    return completion, makespan


# ==================================================
# CDS ALGORITHM
# ==================================================
def cds_algorithm(df):

    proc = df.set_index("Job")

    m = len(proc.columns)

    results = []

    best_makespan = float("inf")
    best_sequence = None
    best_completion = None

    for k in range(1, m):

        virtual_A = proc.iloc[:, :k].sum(axis=1)

        virtual_B = proc.iloc[:, k:].sum(axis=1)

        johnson_df = pd.DataFrame({
            "Job": proc.index,
            "A": virtual_A,
            "B": virtual_B
        })

        sequence = johnson_rule(johnson_df)

        completion, makespan = calculate_completion(
            sequence,
            proc
        )

        results.append({
            "Iterasi": k,
            "Sequence": " → ".join(sequence),
            "Makespan": makespan
        })

        if makespan < best_makespan:
            best_makespan = makespan
            best_sequence = sequence
            best_completion = completion

    result_df = pd.DataFrame(results)

    return (
        result_df,
        best_sequence,
        best_makespan,
        best_completion
    )


# ==================================================
# GANTT DATA
# ==================================================
def create_gantt_data(sequence, proc, completion):

    gantt = []

    for i, job in enumerate(sequence):

        for j, machine in enumerate(proc.columns):

            finish = completion.loc[job, machine]

            process_time = proc.loc[job, machine]

            start = finish - process_time

            gantt.append({
                "Job": job,
                "Machine": machine,
                "Start": start,
                "Finish": finish
            })

    return pd.DataFrame(gantt)


# ==================================================
# HEADER
# ==================================================
st.title("🏭 Campbell Dudek Smith (CDS)")
st.caption("Flow Shop Scheduling")

# ==================================================
# INPUT
# ==================================================
col1, col2 = st.columns(2)

with col1:
    num_jobs = st.number_input(
        "Jumlah Job",
        min_value=2,
        max_value=50,
        value=5
    )

with col2:
    num_machines = st.number_input(
        "Jumlah Mesin",
        min_value=2,
        max_value=10,
        value=3
    )

# ==================================================
# DATAFRAME INPUT
# ==================================================
columns = {"Job": []}

for i in range(num_machines):
    columns[f"M{i+1}"] = []

for j in range(num_jobs):

    columns["Job"].append(f"Job {j+1}")

    for m in range(num_machines):
        columns[f"M{m+1}"].append(1)

default_df = pd.DataFrame(columns)

st.subheader("Input Processing Time")

edited_df = st.data_editor(
    default_df,
    use_container_width=True
)

# ==================================================
# HITUNG CDS
# ==================================================
if st.button("▶ Hitung CDS"):

    try:

        df_jobs = edited_df.copy()

        result_iterasi, best_seq, best_makespan, best_completion = (
            cds_algorithm(df_jobs)
        )

        # ==========================================
        # METRIK
        # ==========================================
        st.subheader("📊 Hasil Terbaik")

        c1, c2 = st.columns(2)

        with c1:
            st.metric(
                "Makespan Minimum",
                best_makespan
            )

        with c2:
            st.metric(
                "Jumlah Job",
                len(best_seq)
            )

        st.success(
            f"Sequence Terbaik : {' → '.join(best_seq)}"
        )

        # ==========================================
        # ITERASI CDS
        # ==========================================
        st.subheader("📋 Hasil Setiap Iterasi CDS")

        st.dataframe(
            result_iterasi,
            use_container_width=True
        )

        # ==========================================
        # COMPLETION MATRIX
        # ==========================================
        st.subheader("⏱ Completion Time Matrix")

        st.dataframe(
            best_completion,
            use_container_width=True
        )

        # ==========================================
        # GANTT CHART
        # ==========================================
        st.subheader("📈 Gantt Chart")

        proc = df_jobs.set_index("Job")

        gantt_df = create_gantt_data(
            best_seq,
            proc,
            best_completion
        )

        fig = px.timeline(
            gantt_df,
            x_start="Start",
            x_end="Finish",
            y="Machine",
            color="Job",
            text="Job"
        )

        fig.update_yaxes(
            autorange="reversed"
        )

        fig.update_layout(
            height=600,
            xaxis_title="Waktu",
            yaxis_title="Mesin"
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    except Exception as e:
        st.error(f"Error : {e}")